name: Build image for Test channel
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate rbuild changelog
        uses: radxa-repo/rbuild-changelog@main
        with:
          product: radxa-zero
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-build-${{ github.run_number }}
          body: |
            This is a test build for internal development.
            Only use when specifically instructed by Radxa support.
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: false
          prerelease: true
          files: .changelog/changelog.md
    outputs:
      release_id: ${{ steps.release.outputs.id }}
  build:
    runs-on: ubuntu-latest
    needs: prepare_release
    strategy:
      matrix:
        boards: [radxa-zero]
        build_systems: [rbuild]
        # distros: [debian, ubuntu]
        suites: [bookworm, jammy]
        flavors: [kde, cli]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload rbuild image
        uses: radxa-repo/rbuild@main
        if: matrix.build_systems == 'rbuild'
        with:
          board: ${{ matrix.boards }}
          # distro: ${{ matrix.distros }}
          suite: ${{ matrix.suites }}
          flavor: ${{ matrix.flavors }}
          release-id: ${{ needs.prepare_release.outputs.release_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-repo: true
          timestamp: t${{ github.run_number }}
